# -*- coding: utf-8 -*-
"""Zomato_Data_Visualization_Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vDHvB6_nJR_ng-bORNdZqD4w8MUWG9A_
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

sns.set(style="whitegrid")

from google.colab import files

uploaded = files.upload()

for fn in uploaded.keys():
  print(f'User uploaded file "{fn}"')

df = pd.read_csv('Zomato-data-.csv')
print("DataFrame 'df' loaded successfully.")

print("First 5 Rows")
print(df.head())

def handleRate(value):
    value = str(value).split('/')
    value = value[0]
    return float(value)

df['rate'] = df['rate'].apply(handleRate)

print(df.info())
print(df.isnull().sum())

plt.figure(figsize=(8,5))
sns.countplot(x='listed_in(type)', data=df, palette="viridis")
plt.title("Restaurant Type Distribution")
plt.xlabel("Type of Restaurant")
plt.ylabel("Count")
plt.xticks(rotation=45)
plt.show()

plt.figure(figsize=(6,4))
sns.countplot(x='online_order', data=df, palette="Set2")
plt.title("Online Order Availability")
plt.xlabel("Online Order")
plt.ylabel("Count")
plt.show()

plt.figure(figsize=(6,4))
plt.hist(df['rate'], bins=10)
plt.title("Ratings Distribution")
plt.xlabel("Rating")
plt.ylabel("Frequency")
plt.show()

grouped = df.groupby('listed_in(type)')['votes'].sum()

plt.figure(figsize=(8,5))
grouped.plot(kind='bar', color='green')
plt.title("Votes by Restaurant Type")
plt.xlabel("Restaurant Type")
plt.ylabel("Total Votes")
plt.xticks(rotation=45)
plt.show()

plt.figure(figsize=(6,5))
sns.boxplot(x='online_order', y='rate', data=df)
plt.title("Rating vs Online Order")
plt.show()

plt.figure(figsize=(8,5))
sns.countplot(x='approx_cost(for two people)', data=df)
plt.xticks(rotation=45)
plt.title("Cost Distribution for Two People")
plt.show()

plt.figure(figsize=(6,5))
sns.scatterplot(x='approx_cost(for two people)', y='rate', data=df)
plt.title("Cost vs Rating")
plt.xlabel("Cost for Two People")
plt.ylabel("Rating")
plt.show()

top10 = df.sort_values(by='votes', ascending=False).head(10)

plt.figure(figsize=(8,5))
sns.barplot(x='votes', y='name', data=top10)
plt.title("Top 10 Restaurants by Votes")
plt.xlabel("Votes")
plt.ylabel("Restaurant Name")
plt.show()

pivot = df.pivot_table(index='listed_in(type)', columns='online_order', aggfunc='size', fill_value=0)

plt.figure(figsize=(7,5))
sns.heatmap(pivot, annot=True, cmap='YlGnBu')
plt.title("Restaurant Type vs Online Order")
plt.show()

plt.figure(figsize=(6,4))
sns.heatmap(df.corr(numeric_only=True), annot=True, cmap='coolwarm')
plt.title("Correlation Heatmap")
plt.show()

max_votes = df['votes'].max()
restaurant = df.loc[df['votes'] == max_votes, 'name']

print("Restaurant with Maximum Votes:")
print(restaurant)